import { mkdirSync, writeFileSync } from 'fs';
import { join } from 'path';
import { format } from 'date-fns';
import type { Digest, DigestItem, GitHubRepo, HackerNewsItem, RedditPost } from '../types.js';
import { OUTPUT_DIR } from '../config.js';

export function generateMarkdownDigest(
  date: string,
  language: 'en' | 'zh',
  repos: GitHubRepo[],
  hnItems: HackerNewsItem[],
  redditPosts: RedditPost[],
  highlights: DigestItem[]
): string {
  const lines: string[] = [];

  // Header
  lines.push(`# NanoClaw Radar - ${date}`);
  lines.push('');

  // Highlights
  if (highlights.length > 0) {
    lines.push(language === 'en' ? '## 🌟 Highlights' : '## 🌟 今日亮点');
    lines.push('');
    for (const highlight of highlights) {
      lines.push(`- **${highlight.title}** - ${highlight.description}`);
    }
    lines.push('');
  }

  // NanoClaw Ecosystem
  const nanoClawRepos = repos.filter((r) => r.owner === 'qwibitai' || r.repo.includes('nanoclaw'));
  if (nanoClawRepos.length > 0) {
    lines.push(language === 'en' ? '## 🤖 NanoClaw Ecosystem' : '## 🤖 NanoClaw 生态');
    lines.push('');
    for (const repo of nanoClawRepos.slice(0, 5)) {
      lines.push(`### ${repo.owner}/${repo.repo}`);
      if (repo.description) lines.push(repo.description);
      lines.push(`- ⭐ ${repo.stars || 0} stars`);
      if (repo.starGrowth) lines.push(`- 📈 +${repo.starGrowth} this week`);
      lines.push('');
    }
  }

  // Claude Ecosystem
  const claudeRepos = repos.filter((r) => r.owner === 'anthropics' || r.repo.includes('claude'));
  if (claudeRepos.length > 0) {
    lines.push(language === 'en' ? '## 🧠 Claude Ecosystem' : '## 🧠 Claude 生态');
    lines.push('');
    for (const repo of claudeRepos.slice(0, 5)) {
      lines.push(`### ${repo.owner}/${repo.repo}`);
      if (repo.description) lines.push(repo.description);
      lines.push(`- ⭐ ${repo.stars || 0} stars`);
      lines.push('');
    }
  }

  // MCP Servers
  const mcpRepos = repos.filter((r) => r.repo.includes('mcp') || r.description?.includes('MCP'));
  if (mcpRepos.length > 0) {
    lines.push(language === 'en' ? '## 🔌 MCP Ecosystem' : '## 🔌 MCP 生态');
    lines.push('');
    for (const repo of mcpRepos.slice(0, 5)) {
      lines.push(`- **${repo.owner}/${repo.repo}** - ${repo.description || ''} (${repo.stars}⭐)`);
    }
    lines.push('');
  }

  // Trending
  const trending = repos.filter((r) => r.trending).slice(0, 10);
  if (trending.length > 0) {
    lines.push(language === 'en' ? '## 📈 Trending' : '## 📈 趋势');
    lines.push('');
    for (let i = 0; i < trending.length; i++) {
      const repo = trending[i];
      lines.push(`${i + 1}. **${repo.owner}/${repo.repo}** - ${repo.stars}⭐`);
      if (repo.description) lines.push(`   ${repo.description}`);
    }
    lines.push('');
  }

  // Community Buzz
  if (hnItems.length > 0 || redditPosts.length > 0) {
    lines.push(language === 'en' ? '## 💬 Community Buzz' : '## 💬 社区动态');
    lines.push('');

    if (hnItems.length > 0) {
      lines.push('### Hacker News');
      lines.push('');
      for (const item of hnItems.slice(0, 5)) {
        lines.push(`- [${item.title}](${item.url || `https://news.ycombinator.com/item?id=${item.id}`}) - ${item.score} points`);
      }
      lines.push('');
    }

    if (redditPosts.length > 0) {
      lines.push('### Reddit Highlights');
      lines.push('');
      for (const post of redditPosts.slice(0, 5)) {
        lines.push(`- r/${post.subreddit}: [${post.title}](${post.url}) - ${post.score} upvotes`);
      }
      lines.push('');
    }
  }

  // Footer
  lines.push('---');
  lines.push('');
  lines.push('Generated by NanoClaw Radar 🔭');
  lines.push('');

  return lines.join('\n');
}

export function saveDigest(content: string, date: string, language: 'en' | 'zh'): void {
  // Save to monthly archive
  const month = date.substring(0, 7);
  const monthDir = join(OUTPUT_DIR, month);
  mkdirSync(monthDir, { recursive: true });

  const filename = `${date}-${language}.md`;
  writeFileSync(join(monthDir, filename), content, 'utf8');

  // Save as latest
  writeFileSync(join(OUTPUT_DIR, 'latest.md'), content, 'utf8');

  console.log(`✅ Saved digest: ${filename}`);
}
